### ISSUE TITLE
<Milestone #1

### ISSUE THREAD

**Issue by hfboyce** [UBC-MDS/DSCI_522-Age-and-Unemployment-Rates#18]
Hi Simon! 

I'll start working on the cleaning script tonight and the viz one to get a bit of a start before Thursday. Are you free to work on this on Friday again?

**Comment by cheukman1207** [comment]
Yes. Friday is perfect.

**Comment by hfboyce** [comment]
Hey Simon I made a great amendment to all the scripts outputting csvs so it does not include row numbering. I also added the confidence interval table in script 4 so we can use it to discuss the findings in our results. 
As per tomorrow I have made a plan for the report and we should be able to get it complete in the evening.

**Comment by cheukman1207** [comment]
Hi Hayley, yes I will go over everything and create the release. Thank you very much!

**Comment by cheukman1207** [comment]
Milestone 1 has been created (https://github.com/UBC-MDS/DSCI_522-Age-and-Unemployment-Rates/releases)
