### ISSUE TITLE
More meaningful commits

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522-Age-and-Unemployment-Rates#31]
You have many commits with the same name as "added addition documentation for the proposal requirements." Make each commit meaningful such that each commit is distinguishable from other commits.

**Comment by hfboyce** [comment]
This was an error when my computer glitched and was not committing. Is there a way I can adjust the commits after they were performed? I noticed this issue and did not know how to adjust it.

**Comment by aimirza** [comment]
https://help.github.com/articles/changing-a-commit-message/

**Comment by hfboyce** [comment]
Thank you!
