### ISSUE TITLE
Additional testing to determine which age groups do not equal.

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522-Age-and-Unemployment-Rates#33]
> If the ANOVA indicates a value lower than our critical value (0.05) we will have to do additional testing to determine which age groups do not equal.

What additional tests were you thinking of?

**Comment by hfboyce** [comment]
We are going to do a pairwise T-test to see which age groups differ. Should we update this in the README.md when we change it to more of a summary instead of a proposal?

**Comment by aimirza** [comment]
Please include the update in the milestone version.

**Comment by hfboyce** [comment]
fixed!
