### ISSUE TITLE
Grammar and spelling

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522-Age-and-Unemployment-Rates#34]
> We will be preforming an ANOVA test to...

Misspelled performing 

> ...and mean squares error which will be use in the calculation..

used, not use

> ...as well as an addition table explaining the outcomes... 

additional

>  ...direct relationship age has on the umemployment rate...

unemployment

**Comment by hfboyce** [comment]
I think there was an error with my release. Can I discuss this with you in lab?
