### ISSUE TITLE
Milestone1 Issues

### ISSUE THREAD

**Issue by aimirza** [UBC-MDS/DSCI_522-Age-and-Unemployment-Rates#56]
**You may close this issue when all issues are resolved and checked.** 

**Mechanics**
- [x] in your main README.md file, provide a brief description of what each command line does, which order scripts are run in, what expected inputs are. Your explanation could include a flow chart/dependecy diagram.

**Reasoning**
- Nice intro!
- [x] You displayed the distribution data and mentioned some descriptive statistics. But what do they tell us about the data? Why did you plot the distributions? 

**Visualization**
- [x] A little more descriptive captions are needed for some figures and tables.  For example: "Figure 1. Mean pregnancy length for first babies pregnancy and for other (non-first baby) pregnancy length. Error bars represent 95% confidence intervals generated by boostrapping.)"

**Quality -- Readability and Documentation**
- [x] Provide a little more descriptive self-documentation in the script 01_clean-data.R. Give us an idea of how it is cleaning the data. The script does explain the cleaning processes in the comments nicely. However, it is a good idea to mention in the self-documentation (at the top of the script). 
- [x] Some of the comments in the scripts have line lengths that are too long. Split the comments into more lines. 
- [x] Each script should mention the names of the files that it produces. 

**Quality -- Robustness and Maintainability**
- [x] Should have a unit test in each script (because we did not clearly mention this in the instructions, we did not deduct points for not having a unit test)

**Grammar and Spelling**
None that I found...

**Comment by hfboyce** [comment]
Currently fixing the length of comment lines in scripts and the file that it produces.

**Comment by hfboyce** [comment]
@ttimbers 
Hi Tiffany,
This is the issue from where my question generated from regarding the unit test. 
Thank you so much!

**Comment by ttimbers** [comment]
> Should have a unit test in each script

Only needed if there exists functions written in the script beyond the main function. Sorry for any confusion.

**Comment by aimirza** [comment]
Your README.md is great and your report is simple and elegant. Good job.

**Comment by aimirza** [comment]
My mistake, no unit tests needed. You dont have functions other than the function main.

**Comment by hfboyce** [comment]
Closing issue all resolved!
