### ISSUE TITLE
Feedbacks from Patrick Tung and Jingyun Chen

### ISSUE THREAD

**Issue by cheukman1207** [UBC-MDS/DSCI_522-Age-and-Unemployment-Rates#61]
Could create a table to describe the variables that are being used, and what type each variable is (e.g., categorical, ordinal, numeric, etc.)

Use more descriptive filename, such as confidence-interval-estimate-table.csv instead of just estimate-table.csv, so readers can understand what the file is for by just looking at the filename.

Remove the unused file (e.g. histogram.png) from the repo to avoid confusion.

In the final report:

In Table 3, why use capital R on "to Reject or fail to Reject the Null hypothesis"?

In Findings, do you mean Is in " Iis there a difference..."

**Comment by hfboyce** [comment]
Hi Simon!
 Tiffany said to keep the histograms in the coding and to keep the images that are output into the "img" file. She said since we have the code to simply keep it for reference.

**Comment by cheukman1207** [comment]
#63 Sure let's keep the histogram. I've fixed all the other issues in the following pull request

**Comment by cheukman1207** [comment]
#63
